version: '3.8'
services:
  germany_visualization:
    build: .
    image: germany_visualization
    restart: on-failure
    environment:
      - REGION=germany
      - BOKEH_ALLOW_WS_ORIGIN=localhost:${GERMANY_PORT},${SERVER_HOST}:${GERMANY_PORT},${GLOBAL_WHITELIST}
      - BOKEH_SSL_CERTFILE=${SSL_CERTFILE}
      - BOKEH_SSL_KEYFILE=${SSL_KEYFILE}
    ports:
      - ${GERMANY_PORT}:5006
  saxony_visualization:
    build: .
    image: saxony_visualization
    restart: on-failure
    environment:
      - REGION=saxony
      - BOKEH_ALLOW_WS_ORIGIN=localhost:${SAXONY_PORT},${SERVER_HOST}:${SAXONY_PORT},${GLOBAL_WHITELIST}
      - BOKEH_SSL_CERTFILE=${SSL_CERTFILE}
      - BOKEH_SSL_KEYFILE=${SSL_KEYFILE}
    ports:
      - ${SAXONY_PORT}:5006
