version: '3.8'
services:
  germany_visualization:
    build: .
    image: germany_visualization
    restart: on-failure
    environment:
      - REGION=germany
      - BOKEH_ALLOW_WS_ORIGIN=localhost:${GERMANY_PORT},${SERVER_HOST}:${GERMANY_PORT}
      - BOKEH_SSL_CERTFILE=${SSL_CERTFILE}
      - BOKEH_SSL_KEYFILE=${SSL_KEYFILE}
    ports:
      - ${GERMANY_PORT}:5006