---
resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.17"
  - name: helm
    type: docker-image
    source:
      repository: typositoire/concourse-helm3-resource

resources:
  - name: rankings-git
    type: git
    icon: github
    source:
      uri: https://github.com/aochen-jli/rankings
  - name: visualizations-image
    type: docker-image
    icon: docker
    source:
      repository: vis-docker-registry:5000/visualizations
      insecure_registries: ["vis-docker-registry:5000"]
      tag_as_latest: true
  - name: nocovid-kubernetes
    type: kubernetes
    icon: kubernetes
    source:
      server: https://173.82.208.79:6443
      namespace: default
      token: ((cluster-auth.token))
      # certificate_authority: ((cluster-auth.certificate-authority-data))
      insecure_skip_tls_verify: true
  - name: nocovid-helm
    type: helm
    icon: ship-wheel
    source:
      cluster_url: https://173.82.208.79:6443
      namespace: default
      cluster_ca: ((cluster-auth.certificate-authority-data))
      token: ((cluster-auth.token))


jobs:
  - name: build-and-push
    plan:
      - get: rankings-git
        trigger: true
      - put: visualizations-image
        params:
          image: image/image.tar
          build: rankings-git

  - name: garbage-collect-registry
    plan:
      - get: visualizations-image
        passed: [build-and-push]
        trigger: true
      - put: nocovid-kubernetes
        params:
          kubectl: >
            exec -it $(kubectl get pods -l app=docker-registry -o custom-columns=:metadata.name)
            --
            /bin/registry garbage-collect /etc/docker/registry/config.yml --delete-untagged

  - name: upgrade-helm
    plan:
      - get: rankings-git
        passed: [build-and-push]
        trigger: true
      - put: nocovid-helm
        params:
          chart: rankings-git/ci/helm/visualizations/
          values: rankings-git/ci/helm/visualizations/values.yaml

  - name: restart-deployments
    plan:
      - get: rankings-git
        passed: [build-and-push]
        trigger: true
      - put: nocovid-kubernetes
        params:
          kubectl: rollout restart -f rankings-git/ci/k8s/visualizations.deployment.yml
          wait_until_ready: 120
