apiVersion: batch/v1
kind: Job
metadata:
  name: prune-host-docker-system
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: alpine
          image: yobasystems/alpine-docker
          command: ["/usr/bin/docker"]
          args: ["system", "prune", "-f"]
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
