page_title: "Germany Visualizations"
visualizations:
  - case:
      title: "COVID Phases in Germany"
      input_path: ./pickles/germany.pkl
      labels:
        - "Green Zone"
        - "Phase 4"
        - "Phase 3"
        - "Phase 2"
        - "Phase 1"
      descriptions:
        - "0 cases in 14 days"
        - "<20 new cases in 14 days"
        - "<200 new cases in 14 days"
        - "<1000 new cases in 14 days"
        - ">1000 new cases in 14 days"
      lower_bounds:
        - 0
        - 1
        - 20
        - 200
        - 1000
      colors:
        - "#25773b"
        - "#8ac541"
        - "#f9cc3c"
        - "#f8961d"
        - "#ef3e24"
