page_title: "Germany Visualizations"
visualizations:
  - case:
      title: "COVID Phasen in Deutschland"
      input_path: ./pickles/germany.pkl
      labels:
        - "Grüne Zone"
        - "Phase 4"
        - "Phase 3"
        - "Phase 2"
        - "Phase 1"
      descriptions:
        - "0 neue Fälle in den letzten 14 Tagen"
        - "<20 neue Fälle in den letzten 14 Tagen"
        - "<200 neue Fälle in den letzten 14 Tagen"
        - "<1000 neue Fälle in den letzten 14 Tagen"
        - ">1000 neue Fälle in den letzten 14 Tagen"
      lower_bounds:
        - 0
        - 1
        - 20
        - 200
        - 1000
      colors:
        - "#25773b"
        - "#8ac541"
        - "#f9cc3c"
        - "#f8961d"
        - "#ef3e24"
