page_title: "Germany Visualizations"  # the HTML page title
horizontal_margin: 25  # the margins on the side of the graph
between_margin: 25  # the margin in between visualizations (if you have multiple)
visualizations:  # visualization config, please look in layout.py for other config options
  - case:  # the label for this visualization, only used for organization. it can be anything (e.g. incidence, foo, bar)
      title: "Sample"  # the title that shows up above the actual graph
      input_path: ./pickles/sample.pkl  # should be written relative to the visualizations folder (the application's working directory)
      labels:
        - ~  # if you don't want the first category to be displayed & sorted by time safe, use a tilde in its place
        - "Grüne Zone"
        - "Phase 4"
        - "Phase 3"
        - "Phase 2"
        - "Phase 1"
      descriptions:
        - ~
        - "0 Fälle in den letzten 14 Tagen"
        - "<20 neue Fälle in den letzten 14 Tagen"
        - "<200 neue Fälle in den letzten 14 Tagen"
        - "<1000 neue Fälle in den letzten 14 Tagen"
        - ">1000 neue Fälle in den letzten 14 Tagen"
      lower_bounds:
        - ~
        - 0
        - 1
        - 20
        - 200
        - 1000
      colors:
        - ~
        - "#25773b"
        - "#8ac541"
        - "#f9cc3c"
        - "#f8961d"
        - "#ef3e24"
